version: "2"
services:
  builder:
    image: openlmis/requisition-refui
    volumes:
      - '.:/app'
    command:
      - './build.sh'
  image:
    build: .
    image: openlmis/requisition-refui-prod

  devImage:
    build: ./developer/
    image: openlmis/requisition-refui-prod