version: "2"
services:
#  consul:
#    image: gliderlabs/consul-server
#    command: -server -bootstrap
#    ports:
#      - "8500:8500"
#  registrator:
#    image: gliderlabs/registrator
#    command: -internal consul://consul:8500
#    links:
#      - consul
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock
#  requisition:
#    image: openlmis/requisition
#    env_file: .env
#    environment:
#      - VIRTUAL_HOST=localhost
#      - VIRTUAL_LOCATION=requisition
#    links:
#      - db
#      - log
#      - auth
#  db:
#    image: openlmis/postgres
#    env_file: .env
#  log:
#   image: openlmis/rsyslog
#    volumes:
#      - '../logs/requisition:/var/log'
#  auth:
#    image: openlmis/auth
#    environment:
#      - VIRTUAL_HOST=localhost
#      - VIRTUAL_LOCATION=auth
#    env_file: .env
  requisition-refui:
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
#      - ./build:/usr/share/nginx/html
#      - ./build2:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./nginx.tmpl:/app/nginx.tmpl:ro